# Generated by Django 3.1.1 on 2020-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_auto_20200922_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='nome',
        ),
        migrations.AddField(
            model_name='livro',
            name='titulo',
            field=models.CharField(default=1, max_length=150, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
