# Generated by Django 3.1.1 on 2020-09-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_remove_autor_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='idade',
            field=models.IntegerField(default=1, verbose_name='idade'),
            preserve_default=False,
        ),
    ]
